@startuml
'https://plantuml.com/class-diagram
class Game
class Map
class Player
class Bot
class Game
class Algorithm
class Flag


class Game {
    - map : Map                    // map of the game
    - player1 : Player             // player 1 of the game
    - player2 : Player             // player 2 of the game
    - currentPlayer : Player       // current player of the game
    - round : int                  // current round of the game
    + getters() and setters()
    + startGame() : void
    + checkGameOver() : boolean
    + getWinner() : Player
}

class Map {
    - graphMap : Newtork<Location>                   // graph representing the map
    - flagLocations : UnorderedLinkedList<Location>  // list of flag locations(vertices) on the map
    + generateMap() : Map
    + importMap() : void
    + exportMap() : void
}

'Classe Correta Não Alterar'
class Location {
    - positionX : int                 // x coordinate of the location on the map
    - positionY : int                 // y coordinate of the location on the map
    + getters() and setters()
}
'Classe Correta Não Alterar'
class Flag {
    - location : Location              // location of the flag on the map
    - owner : Player                   // player who owns the flag
    + getters() and setters()
}

class Player {
    - id : int                         // unique id of the player
    - name : String                    // name of the player
    - bots : OrderedLinkedList<Bot>  // list of bots controlled by the player
    + getters() and setters()
}
class Bot {
    - id : int                         // unique id of the bot
    - algorithm : Algorithm            // algorithm used by the bot to move
    - location : Location              // location of the bot on the map
    + getters() and setters()

class Algorithm{
    class MoveToBlock{
        + move() : void
    }
    class MoveByShortestPath{
    + move() : void
    }
    class MoveByRandomPath{
    + move : void
    }
    class MoveByLongestPath{
    + move() : void
    }
}






@enduml
























class CaptureTheFlag{
  Map map ;
  Player player1m, player2 ;

    public CaptureTheFlag() {
        this.map = new Map;
        this.player1 = new Player;
        this.player2 = new Player;
    }
}

