/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package game;

import org.graphstream.graph.Edge;
import org.graphstream.graph.Node;

import java.util.stream.Stream;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());
    }
}